version: "3.9"
services:
  frontend:
    image: hpandher613/training-crm-front
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST_API=http://localhost:3000
    depends_on:
      - backend
  backend:
    image: hpandher613/training-crm-back
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://admin:password@mongo:27017/trainingcrm?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: